name: Terraform Azure Deployment

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      action:
        description: "Choose apply or destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    env:
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      -- name: Azure Login
  uses: azure/login@v2
  with:
    client-id: 2ad8b30b-45b7-4ffc-9e79-389fb357373c
    tenant-id: 7fa45e59-ccd9-43fb-8d9f-d639b73dcbea
    subscription-id: 4c3c4430-0ce6-48bc-8e33-1947f3876ebd
    client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
